### ISSUE TITLE
Add scheme to Material Theme

### ISSUE THREAD

**Issue by chrisburton** [mbixby/facebook-color-scheme#4]
It would be awesome if you could get in contact with @equinusocio to add this scheme to Material Theme. I've created a simple project showcasing the look of Material and the Facebook scheme integration [here](https://github.com/christopherburton/Jeffrey-Way-Theme) and I think it looks great. Would this be possible?

**Note:** I slightly edited the scheme to match Material Theme.

**Comment by equinusocio** [comment]
I'm sorry but Material Theme will not provide other color schemes. Oceanic Next was also removed from the release 3 because the theme use a custom scheme builder with predefinited color palettes. If you want to use this (awesome) color scheme just download it and customize it to match the Material Theme UI. 👍
